kind: pipeline
name: defaultworkspace:
  base: /go
  path: /home/madhurkatyal/work/src/Sort-And-Search steps:
  - name: test
    image: golang
    commands:
      - go get
      - go test  - name: build
    image: golang
    commands:
      - go get
      - go build -o output
      - chmod +x output  - name: run
    image: golang
    commands:
      - go get
      - go build -o output
      - chmod +x output
      - ./output